// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDejMakrXXg_-g9bWcdzsblp3QPIRhERtE',
    appId: '1:458604772374:web:c8b63bad26d41dfb4dc937',
    messagingSenderId: '458604772374',
    projectId: 'lh-hrm',
    authDomain: 'lh-hrm.firebaseapp.com',
    storageBucket: 'lh-hrm.appspot.com',
    measurementId: 'G-75LXTXYW97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgBmW_8IUYY-SYKQWJy-9zcoKxz2Nksn8',
    appId: '1:458604772374:android:72ff02a3b6da06ab4dc937',
    messagingSenderId: '458604772374',
    projectId: 'lh-hrm',
    storageBucket: 'lh-hrm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOW5hWT7xQ02qSP3sIYajqbtBG73U5obo',
    appId: '1:458604772374:ios:357c2b353d2cacbd4dc937',
    messagingSenderId: '458604772374',
    projectId: 'lh-hrm',
    storageBucket: 'lh-hrm.appspot.com',
    iosBundleId: 'com.example.homepageHrm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOW5hWT7xQ02qSP3sIYajqbtBG73U5obo',
    appId: '1:458604772374:ios:357c2b353d2cacbd4dc937',
    messagingSenderId: '458604772374',
    projectId: 'lh-hrm',
    storageBucket: 'lh-hrm.appspot.com',
    iosBundleId: 'com.example.homepageHrm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDejMakrXXg_-g9bWcdzsblp3QPIRhERtE',
    appId: '1:458604772374:web:b45e2acd887d9d824dc937',
    messagingSenderId: '458604772374',
    projectId: 'lh-hrm',
    authDomain: 'lh-hrm.firebaseapp.com',
    storageBucket: 'lh-hrm.appspot.com',
    measurementId: 'G-CD5ZHKZBVS',
  );
}
